name: Docker Image CI

on: "push"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --pull --rm -f "Image/Dockerfile" -t flutterdevcontainer:${{env.GITHUB_SHA}} "Image"
    
    - name: Push docker image to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: gdscparuluniversity
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - run: |
        docker tag flutterdevcontainer:${{env.GITHUB_SHA}} ghcr.io/gdscparuluniversity/flutterdevcontainer:${{env.GITHUB_SHA}}
        docker push ghcr.io/gdscparuluniversity/flutterdevcontainer:${{env.GITHUB_SHA}}
